nexus_dependencies_packages:
  - python3
  - python3-venv
  - python3-dev
  - python3-pip
  - python3-six
  - python3-dbus
  - avahi-daemon
  - avahi-utils
  - exfatprogs
  - nfs-common
  - nfs-kernel-server
  - dnsmasq
  - wireguard
