[master]
nexus-n3-master ansible_host=nexus-n3-master.local ansible_user=nexusn3 ansible_become=true ansible_become_method=sudo ansible_python_interpreter=/usr/bin/python3.12

#[workers]
#nexus-n3-worker-02 ansible_host=nexus-n3-worker-02.local ansible_user=nexusn3 ansible_become=true ansible_become_method=sudo ansible_python_interpreter=/usr/bin/python3.12

#[ai_nodes]
#nexus-n3-ai-01 ansible_host=nexus-n3-ai-01.local ansible_user=nexusn3 ansible_become=true ansible_become_method=sudo ansible_python_interpreter=/usr/bin/python3.12
